#!/usr/bin/env python
#-*- coding: utf-8 -*-

# Author: youngtrips(youngtrips@gmail.com)
# Created Time:  2012-06-05
# File Name: test.py
# Description: 
#

import core
import sys
import os
LIBPATH = os.path.join(os.path.dirname(sys.argv[0]), 'lib')
sys.path.insert(0, LIBPATH) 
from lib import cmdln

class Zephyr(cmdln.Cmdln):
    """Usage:
        zephyr command [args...]
        zephyr help command

    ${command_list}
    ${help_list}
    """
    name = "zephyr"

    def __init__(self, *args, **kwargs):
        cmdln.Cmdln.__init__(self, *args, **kwargs)
        cmdln.Cmdln.do_help.aliases.append("h")

        print sys.argv[0]
        #os.environ['ZEPHYR_BIN_DIR'] = os.path.basename(sys.argv[0])

        print 'bin:[%s]' % (os.path.basename(sys.argv[0]))

        """
        os.environ['ZEPHYR_THEME_DIR'] = os.path.join(os.getenv('ZEPHYR_BIN_DIR'), 'themes')
        os.environ['ZEPHYR_WORK_DIR']  =  os.getcwd()
        os.environ['ZEPHYR_CONFIG_DIR'] = os.path.join(os.getenv('ZEPHYR_WORK_DIR', '.zephyr'))
        """


    @cmdln.option("-t", "--theme",
                  help="choose a theme for blog")
    def do_init(self, subcmd, opts, *args):
        """Initialize blog path.

        usage:
            init PATH...
        ${cmd_option_list}
        """
        path = ''
        if len(args) == 0:
            path = os.getcwd()
        elif len(args) == 1:
            path = args[0]
        else:
            print 'invalid path'
            return
        theme = 'default'
        if opts.theme:
            theme = opts.theme
        #print theme, path
        core.init_sketch_path(path)

    @cmdln.option("-p", "--path",
                  help="set blog path")
    @cmdln.option("-t", "--title",
                  help="Set display title for post")
    def do_newpost(self, subcmd, opts, *args):
        """Create a new postfile with Markdown format.

        usage:
            newpost POSTNAME [--path=PATH] [--title=TITLE]
        ${cmd_option_list}
        """

        if len(args) != 1:
            return
        postname = args[0]
        title = ''
        if opts.title:
            title = opts.title
        path = os.getcwd()
        if opts.path:
            path = opts.path
        core.new_post(postname, title, path)

    @cmdln.option("-p", "--path",
                  help="Set blog path")
    def do_newpage(self, subcmd, opts, *args):
        """Create a new page.

        usage:
            newpage pagename [--path=PATH]
        ${cmd_option_list}
        """

        #print "'zephyr %s' opts: %s" % (subcmd, opts)
        #print "'zephyr %s' args: %s" % (subcmd, args)

    def do_publish(self, subcmd, opts, *args):
        """Publish your posts

        usage:
            publish [PATH]
        """
        #print "'zephyr %s' opts: %s" % (subcmd, opts)
        #print "'zephyr %s' args: %s" % (subcmd, args)

        path = ''
        if len(args) == 0:
            path = os.getcwd()
        elif len(args) == 1:
            path = args[0]
        else:
            print 'invalid args'
            return
        core.publish(path)

if __name__ == "__main__":
    zephyr = Zephyr()
    #print os.getenv('ZEPHYR_WORK_DIR')
    #print os.getenv('ZEPHYR_THEME_DIR')

    sys.exit(zephyr.main())

